[package]
name = "library"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "library"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

library_integrity = { workspace = true } 
